openapi: 3.0.3
info:
  title: Сервис управления воротами 
  description: Управление воротами (запирать и отпирать автоматические ворота)
  version: 1.0.11
servers:
  - url: https://localhost:8084/api/v1
paths: 
  /gates:
    put:
      tags:
        - Gate
      summary: Update an existing Gate
      description: Update an existing Gate by Id
      operationId: updateGate
      security: 
        - gate_auth: 
          - write_Gate
      requestBody:
        description: Update an existent Gate 
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Gate'
          application/xml:
            schema:
              $ref: '#/components/schemas/Gate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Gate'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gate'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Gate'
        '400':
          description: Invalid ID supplied
        '404':
          description: Gate not found
        '422':
          description: Validation exception
        '500':
          description: Server exception
    post:
      tags:
        - Gate
      summary: add Gate
      description: add new Gate
      operationId: addGate
      security: 
        - gate_auth: 
          - write_Gate
      requestBody:
        description: add Gate 
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Gate'
          application/xml:
            schema:
              $ref: '#/components/schemas/Gate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Gate'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gate'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Gate'
        '422':
          description: Validation exception
        '500':
          description: Server exception
    get:
      tags:
        - Gate
      summary: Returns array Gate by User
      description: Returns array Gate by User
      operationId: getGateByUser
      security: 
        - gate_auth: 
          - read_Gate
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Gate'          
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Gate'
        '500':
          description: Server exception
  /gates/{GateId}:
    get:
      tags:
        - Gate
      summary: Find Gate by ID
      description: Returns a single SmartHome
      operationId: getGateById
      security: 
        - gate_auth: 
          - read_Gate
      parameters:
        - name: GateId
          in: path
          description: ID of GateId to return
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gate'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Gate'
        '400':
          description: Invalid ID supplied
        '404':
          description: SmartHome not found
        '500':
          description: Server exception
    delete:
      tags:
        - Gate
      summary: Deletes a Gate
      description: delete a Gate
      operationId: deleteGate
      security: 
        - gate_auth: 
          - delete_Gate
      parameters:
        - name: GateId
          in: path
          description: ID of GateId to return
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'          
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '400':
          description: Invalid GateId
        '500':
          description: Server exception

components:
  schemas:
    Gate:
      required:
        - Name
        - SmartHomeId
      type: object
      properties:
        Id:
          description: The unique identifier for Gate. (A UUID specified by RFC4122)
          type: string
          format: uuid
          example: 1234f71f-22ae-43b4-92f3-f4af77cdf777
        SmartHomeId:
          description: The unique identifier for SmartHome. (A UUID specified by RFC4122)
          type: string
          format: uuid
          example: 1234f71f-22ae-43b4-92f3-f4af77cdf772
        Name:
          type: string
          example: Главные ворота 
        IsOpen:
          type: boolean 
          description: ворота открыты/закрыты 
          example: true
      xml:
        name: Gate
    ApiResponse:
      type: object
      properties:
        GateId:
          type: string
          format: uuid
        Message:
          type: string
      xml:
        name: ApiResponse
  examples:
        ApiResponse:
          value:
            GateId: 1234f71f-22ae-43b4-92f3-f4af77cdf444
            Message:  delete is successful

  securitySchemes:
    gate_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://localhost:8089/oauth/authorize
          scopes:
            write_Gate: modify Gate
            read_Gate: read Gate
            delete_Gate: delete Gate
